apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-update-client
  namespace: go-client
  labels:
    app: go-update-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-update-client
  template:
    metadata:
      labels:
        app: go-update-client
    spec:
      containers:
        - name: go-update-client
          image: gaivnshark/goupdateclient:0.1